### ISSUE TITLE
Cannot compile against Harfbuzz 1.0.6

### ISSUE THREAD

**Issue by alerque** [simoncozens/sile#186]
I just realized that my testing in #181 is faulty because I wasn't actually running the version of SILE I thought I was … because it hadn't actually compiled when I updated the repo … because at some point it stopped compiling against the latest Harfbuzz version. Testing this in Travis shows that bumping from 1.0.4 to 1.0.6 breaks SILE's make step. Relevant make output includes:

    fontmetrics.c: In function ‘get_typographic_extents’:
    fontmetrics.c:41:3: error: unknown type name ‘hb_font_extents_t’
       hb_font_extents_t metrics = {0,0,0};
       ^
    fontmetrics.c:41:34: warning: excess elements in scalar initializer
       hb_font_extents_t metrics = {0,0,0};
                                      ^
    fontmetrics.c:41:34: note: (near initialization for ‘metrics’)
    fontmetrics.c:41:36: warning: excess elements in scalar initializer
       hb_font_extents_t metrics = {0,0,0};
                                        ^
    fontmetrics.c:41:36: note: (near initialization for ‘metrics’)
    fontmetrics.c:44:3: warning: implicit declaration of function ‘hb_font_get_extents’ [-Wimplicit-function-declaration]
       hb_font_get_extents(hbFont, &metrics);
       ^
    fontmetrics.c:45:21: error: request for member ‘ascender’ in something not a structure or union
       ascender = metrics.ascender / (double)upem;
                         ^
    fontmetrics.c:46:22: error: request for member ‘descender’ in something not a structure or union
       descender = metrics.descender / (double)upem;
                          ^

**Comment by alerque** [comment]
Git bisect turns up 9abada1 as the first bad commit for this issue.

**Comment by behdad** [comment]
You probably need this:
https://github.com/behdad/harfbuzz/pull/165

Sile is using a patched HB, and the patch became stale after my changes.  Simon kindly updated the patch.  I'll try to finish and merge it tomorrow.

**Comment by simoncozens** [comment]
Yep, and the ifdef should refer to the *next* version of Harfbuzz.

**Comment by simoncozens** [comment]
OK, that commit should make the font metrics code fall back to FreeType.

**Comment by alerque** [comment]
Confirmed working.
